<?php

use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Form\FormBase;
use Drupal\Component\Utility\UrlHelper;

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\Component\Utility\Html;





function oil_survey_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  if ($form_id == 'contact_message_feedback_form') {
    
  }

  if ($form_id == 'contact_message_feedback_form') {
    $form['name']['#title'] = 'NAME*';
    $form['mail']['#title'] = 'EMAIL*';
    $form['message']['widget'][0]['value']['#title'] = 'HOW CAN WE HELP?*';
    $form['actions']['submit']['#value'] = 'SEND';
    $form['subject']['widget']['#required'] = FALSE;
    $form['subject']['#access'] = FALSE;
  }

	if ($form_id == 'user_register_form') {
    $form['field_monthly']['widget'][0]['value']['#title']= t('Dialing Code');    
	  $form['actions']['submit']['#submit'][] = 'oil_survey_contact_submit';
	  $form['actions']['submit']['#value'] = t('START');
    $form['account']['mail']['#description'] = t('');
    $form['account']['pass']['#description'] = t('');
    $form['account']['mail']['#attributes']['placeholder'] = t('please fill...');
  }

  if ($form_id == 'contact_message_feedback_form') {
    $form['name']['#plain_text'] = t('');
    $form['mail']['#plain_text'] = t('');
    $form['name']['#type'] = 'textfield';
    $form['mail']['#type'] = 'textfield';
    $form['name']['#value'] = t('');
    $form['mail']['#value'] = t('');
  }

}




 function register_alter_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
     case 'user_register_form':
       $form['account']['pass']['#process'][] = array('form_process_password_confirm', 'oil_survey_register_alter_password_confirm');
       break;      
  }
  	
}

function oil_survey_register_alter_password_confirm($element) {
   $element['pass1']['#title'] = t("Password");
   $element['pass2']['#title'] = t("");
   return $element;
 }


function oil_survey_contact_submit($form, \Drupal\Core\Form\FormStateInterface &$form_state) {
  $host = \Drupal::request()->getHost();
  $url = Url::fromUri('http://' . $host . '/questionary');
  $form_state->setRedirectUrl($url);
}


function oil_survey_theme($existing, $type, $theme, $path) {
  
  return array(    
    'page_result' => array(
      'variables' => array(
        'text' => null,
        'form' => null,
        'feedback' => null,
        ),
      'template' => 'page_result',
    ),     

    'top_header_block' => array(
      'variables' => array(
        'items' => null,
        ),
      'template' => 'top_header_block',
    ),         
    
    'hslider_block' => array(
      'variables' => array(
        'items' => null,
      ),
      'template' => 'hslider_block',
    ),

    'footer_block' => array(
      'variables' => array(
        'items' => null,
      ),
      'template' => 'footer_block',
    ),
  );
}
