<?php

use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Form\FormBase;
use Drupal\Component\Utility\UrlHelper;

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\Component\Utility\Html;





/**
 * Do a bit of processing for the password_confirm element.
 * Original processing happens in expand_password_confirm()
 */


function oil_survey_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	if ($form_id == 'user_register_form') {
	  $form['actions']['submit']['#submit'][] = 'oil_survey_contact_submit';
	  $form['actions']['submit']['#value'] = t('Next step');
    $form['account']['mail']['#description'] = t('');
    $form['account']['pass']['#description'] = t('');
    $form['account']['mail']['#attributes']['placeholder'] = t('please fill...');
  }

  if ($form_id == 'contact_message_feedback_form') {
    $form['name']['#plain_text'] = t('');
  }

}

 function register_alter_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
     case 'user_register_form':
       // Here we need to provide an extra #process handler to allow us to modify
       // the password element that FAPI expands.
       $form['account']['pass']['#process'][] = array('form_process_password_confirm', 'register_alter_password_confirm');
       kint($form);
       break;
   }
  
	
}

function register_alter_password_confirm($element) {
       $element['pass1']['#title'] = t("Psssssssassword");
   $element['pass2']['#title'] = t("Repsssssssssssseat password");
    return $element;

}

function oil_survey_contact_submit($form, \Drupal\Core\Form\FormStateInterface &$form_state) {
  $host = \Drupal::request()->getHost();
  $url = Url::fromUri('http://' . $host . '/questionary');
  $form_state->setRedirectUrl($url);
}


function oil_survey_theme($existing, $type, $theme, $path) {
  // if (!\Drupal::currentUser()->id()) {
  //   $form = Drupal::formBuilder()->getForm(Drupal\user\Form\UserLoginForm::class) ; 
  //   $render = Drupal::service('renderer');
  //   $variables['login_form'] = $render->renderPlain($form);
    
  // }
  return array(
    'page_result' => array(
      'variables' => array(
        'text' => null,
        ),
      'template' => 'page_result',
    ),   

    'top_header_block' => array(
      'variables' => array(
        'items' => null,
        ),
      'template' => 'top_header_block',
    ),         
    
    'hslider_block' => array(
      'variables' => array(
        'items' => null,
      ),
      'template' => 'hslider_block',
    ),

    'footer_block' => array(
      'variables' => array(
        'items' => null,
      ),
      'template' => 'footer_block',
    ),
  );
}
