<?php


  use Drupal\Core\Mail\MailManagerInterface;
  use Drupal\Component\Utility\SafeMarkup;
  use Drupal\Component\Utility\Html;
  use Drupal\node\Entity\Node;




  /**
   * Implements hook_mail().
   */
  function feedback_form_mail($key, &$message, $params) {
    $val['help'] = \Drupal::state()->get('help');
    $val['full_name'] = \Drupal::state()->get('full_name');
    $options = array (
      'langcode' => $message['langcode'],
    );
    switch ($key) {
      case 'comment_alert_mail':
        $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
        $message['from'] = "info@comparefueltestkits.com";
        $message['subject'] = "Your Fuel Test Kit Recommendation";
        $theme_body = array(
          '#theme' => 'comment_alert_mail',
          '#text' => $val,
          '#title' => $params['node_title'],

        );
        $mail_body = drupal_render($theme_body);
        $message['body'][] = Html::escape($mail_body);
        break;
    };
  }

  /**
   * Implements hook_entity_insert().
   */

  function feedback_form_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
    if ($entity->getEntityTypeId() !== 'node' || ($entity->getEntityTypeId() === 'node' && $entity->bundle() !== 'feedback')) {
      return;
    }
    $key = 'comment_alert_mail';
    $mailManager = \Drupal::service('plugin.manager.mail');
    $module = 'feedback_form';

    $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    $to = $user->get('mail')->value;
    $params['node_title'] = 'Oil Compare';
    $langcode = \Drupal::currentUser()->getPreferredLangcode();
    $send = true;
    $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
  }


  /**
   * Implements hook_theme().
   */

  function feedback_form_theme($existing, $type, $theme, $path) {
     $val = \Drupal::state()->get('help');
     $variables['text'] = $val;
    return [
      'comment_alert_mail' => [
        'variables' => [
          'text' => null
        ],
      ],
    ];
  }
